# application-dev.yml
server:
  port: ${SERVER_PORT:8084}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db-asistencias}:${DB_PORT:5437}/${DB_NAME:db_asistencia_certificados}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:ms_asistencias}
    password: ${DB_PASSWORD:1324}
    driver-class-name: com.mysql.cj.jdbc.Driver